<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE faqs [
        <!ELEMENT faqs (faq+)>
        <!ELEMENT faq (question, answer)>
        <!ELEMENT question (#PCDATA)>
        <!ELEMENT answer (#PCDATA)>
        ]>

<faqs>
    <faq>
        <question>question1</question>
        <answer>answer1</answer>
    </faq>
    <faq>
        <question>question2</question>
        <answer>answer2</answer>
    </faq>
    <faq>
        <question>question3</question>
        <answer>answer3</answer>
    </faq>
    <faq>
        <question>question4</question>
        <answer>answer4</answer>
    </faq>
</faqs>
